// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pglvcyrqxuaxstdsioqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnbHZjeXJxeHVheHN0ZHNpb3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNjgyOTgsImV4cCI6MjA3Nzk0NDI5OH0.TTlVbCNBN6ITlNKCdSVAFJR2vEPDaN1lVagpu8rfKks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});